#ifndef MINI_EXPRESS_H
#define MINI_EXPRESS_H

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    const char *method;
    const char *path;
    const char *body;
} Request;

/* Response stores the HTTP status and JSON payload generated by a handler. */
typedef struct {
    int status_code;
    char response_buf[4096];
} Response;

/* Route handlers receive a parsed request and fill the response object. */
typedef void (*RouteHandler)(Request *, Response *);

/* Register handlers for exact-path GET and POST routes. */
void app_get(const char *path, RouteHandler handler);
void app_post(const char *path, RouteHandler handler);

/* Match a request against the route table and invoke the registered handler. */
void app_dispatch_request(const char *method, const char *path,
                          const char *body, Response *res);

/* Convenience helpers for common JSON success and error responses. */
void res_success(Response *res, const char *message);
void res_error(Response *res, int status_code, const char *error_message);

#ifdef __cplusplus
}
#endif

#endif
